CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(50),
    avatar VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(100),
    status INTEGER DEFAULT 1,
    role VARCHAR(20) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teacher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    teacher_no VARCHAR(20),
    name VARCHAR(50),
    gender VARCHAR(10),
    birthday DATE,
    phone VARCHAR(20),
    email VARCHAR(100),
    title VARCHAR(40),
    department VARCHAR(100),
    hire_date DATE,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR(50),
    class_code VARCHAR(20),
    grade INTEGER,
    major VARCHAR(100),
    teacher_id BIGINT,
    room VARCHAR(50),
    student_count INTEGER DEFAULT 0,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    student_no VARCHAR(20),
    name VARCHAR(50),
    gender VARCHAR(10),
    birthday DATE,
    id_card VARCHAR(18),
    phone VARCHAR(20),
    email VARCHAR(100),
    address VARCHAR(255),
    class_id BIGINT,
    enrollment_date DATE,
    graduation_date DATE,
    status VARCHAR(20),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100),
    course_code VARCHAR(20),
    credit DECIMAL(4,1),
    hours INTEGER,
    category VARCHAR(20),
    description VARCHAR(500),
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course_arrangement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    teacher_id BIGINT,
    class_id BIGINT,
    semester VARCHAR(30),
    schedule VARCHAR(100),
    room VARCHAR(50),
    capacity INTEGER DEFAULT 50,
    enrolled_count INTEGER DEFAULT 0,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    course_arrangement_id BIGINT,
    usual_score DECIMAL(5,2),
    midterm_score DECIMAL(5,2),
    final_score DECIMAL(5,2),
    total_score DECIMAL(5,2),
    gpa DECIMAL(3,2),
    exam_time TIMESTAMP,
    status VARCHAR(20),
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    course_arrangement_id BIGINT,
    attendance_date DATE,
    status VARCHAR(20),
    check_in_time TIME,
    check_out_time TIME,
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leave_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    course_arrangement_id BIGINT,
    leave_type VARCHAR(20),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    reason VARCHAR(500),
    attachment VARCHAR(255),
    status VARCHAR(20),
    approver_id BIGINT,
    approve_time TIMESTAMP,
    approve_remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS announcement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200),
    content CLOB,
    type VARCHAR(20),
    target_role VARCHAR(20),
    target_class_id BIGINT,
    priority INTEGER DEFAULT 0,
    author_id BIGINT,
    view_count INTEGER DEFAULT 0,
    is_top INTEGER DEFAULT 0,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
