CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(50),
    avatar VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(100),
    status INTEGER DEFAULT 1,
    role VARCHAR(20) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teacher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    teacher_no VARCHAR(20),
    name VARCHAR(50),
    gender VARCHAR(10),
    birthday DATE,
    phone VARCHAR(20),
    email VARCHAR(100),
    title VARCHAR(40),
    department VARCHAR(100),
    hire_date DATE,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR(50),
    class_code VARCHAR(20),
    grade INTEGER,
    major VARCHAR(100),
    teacher_id BIGINT,
    room VARCHAR(50),
    student_count INTEGER DEFAULT 0,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    student_no VARCHAR(20),
    name VARCHAR(50),
    gender VARCHAR(10),
    birthday DATE,
    id_card VARCHAR(18),
    phone VARCHAR(20),
    email VARCHAR(100),
    address VARCHAR(255),
    class_id BIGINT,
    enrollment_date DATE,
    graduation_date DATE,
    status VARCHAR(20),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100),
    course_code VARCHAR(20),
    credit DECIMAL(4,1),
    hours INTEGER,
    category VARCHAR(20),
    description VARCHAR(500),
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course_arrangement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    teacher_id BIGINT,
    class_id BIGINT,
    semester VARCHAR(30),
    schedule VARCHAR(100),
    room VARCHAR(50),
    capacity INTEGER DEFAULT 50,
    enrolled_count INTEGER DEFAULT 0,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    course_arrangement_id BIGINT,
    usual_score DECIMAL(5,2),
    midterm_score DECIMAL(5,2),
    final_score DECIMAL(5,2),
    total_score DECIMAL(5,2),
    gpa DECIMAL(3,2),
    exam_time TIMESTAMP,
    status VARCHAR(20),
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    course_arrangement_id BIGINT,
    attendance_date DATE,
    status VARCHAR(20),
    check_in_time TIME,
    check_out_time TIME,
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leave_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    course_arrangement_id BIGINT,
    leave_type VARCHAR(20),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    reason VARCHAR(500),
    attachment VARCHAR(255),
    status VARCHAR(20),
    approver_id BIGINT,
    approve_time TIMESTAMP,
    approve_remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS announcement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200),
    content CLOB,
    type VARCHAR(20),
    target_role VARCHAR(20),
    target_class_id BIGINT,
    priority INTEGER DEFAULT 0,
    author_id BIGINT,
    view_count INTEGER DEFAULT 0,
    is_top INTEGER DEFAULT 0,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    operation VARCHAR(100),
    method VARCHAR(500),
    params CLOB,
    ip VARCHAR(50),
    duration BIGINT,
    status INTEGER,
    error_msg CLOB,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_teacher_user_id ON teacher(user_id);
CREATE INDEX IF NOT EXISTS idx_student_user_id ON student(user_id);
CREATE INDEX IF NOT EXISTS idx_student_class_id ON student(class_id);

CREATE INDEX IF NOT EXISTS idx_arrangement_teacher ON course_arrangement(teacher_id);
CREATE INDEX IF NOT EXISTS idx_arrangement_class_semester ON course_arrangement(class_id, semester);

CREATE INDEX IF NOT EXISTS idx_score_student_create ON score(student_id, create_time);
CREATE INDEX IF NOT EXISTS idx_score_arrangement_create ON score(course_arrangement_id, create_time);
CREATE INDEX IF NOT EXISTS idx_score_total_score ON score(total_score);

CREATE INDEX IF NOT EXISTS idx_attendance_student_date ON attendance(student_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_arrangement_date ON attendance(course_arrangement_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_status_date ON attendance(status, attendance_date);

CREATE INDEX IF NOT EXISTS idx_leave_student_status_time ON leave_request(student_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_leave_arrangement_status_time ON leave_request(course_arrangement_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_leave_status_time ON leave_request(status, create_time);

CREATE INDEX IF NOT EXISTS idx_announcement_status_time ON announcement(status, create_time);
CREATE INDEX IF NOT EXISTS idx_announcement_target_role ON announcement(target_role);
CREATE INDEX IF NOT EXISTS idx_announcement_time_window ON announcement(start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_sys_log_create_time ON sys_log(create_time);
CREATE INDEX IF NOT EXISTS idx_sys_log_user_time ON sys_log(user_id, create_time);
CREATE INDEX IF NOT EXISTS idx_score_total_create ON score(total_score, create_time);
CREATE INDEX IF NOT EXISTS idx_score_arrangement_total ON score(course_arrangement_id, total_score);
CREATE INDEX IF NOT EXISTS idx_attendance_status_scope_date ON attendance(status, course_arrangement_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_leave_pending_create ON leave_request(status, create_time);
CREATE INDEX IF NOT EXISTS idx_leave_arrangement_pending ON leave_request(course_arrangement_id, status, create_time);
