CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    username VARCHAR(50) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(50),
    avatar VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(100),
    status INTEGER DEFAULT 1,
    role VARCHAR(20) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teacher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id VARCHAR(50),
    teacher_no VARCHAR(20) PRIMARY KEY,
    name VARCHAR(50),
    gender VARCHAR(10),
    birthday DATE,
    phone VARCHAR(20),
    email VARCHAR(100),
    title VARCHAR(40),
    department VARCHAR(100),
    college_id BIGINT,
    hire_date DATE,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    class_name VARCHAR(50),
    class_code VARCHAR(16) PRIMARY KEY,
    grade INTEGER,
    major_code VARCHAR(8),
    college_id BIGINT,
    teacher_id BIGINT,
    room VARCHAR(50),
    student_count INTEGER DEFAULT 0,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id VARCHAR(50),
    student_no VARCHAR(20) PRIMARY KEY,
    name VARCHAR(50),
    gender VARCHAR(10),
    birthday DATE,
    id_card VARCHAR(18),
    phone VARCHAR(20),
    email VARCHAR(100),
    address VARCHAR(255),
    class_id VARCHAR(16),
    enrollment_date DATE,
    graduation_date DATE,
    status VARCHAR(20),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100),
    course_code VARCHAR(20),
    credit DECIMAL(4,1),
    hours INTEGER,
    category VARCHAR(20),
    description VARCHAR(500),
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course_arrangement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arrangement_code VARCHAR(15),
    course_id BIGINT,
    teacher_id BIGINT,
    class_id VARCHAR(16),
    semester VARCHAR(30),
    schedule VARCHAR(100),
    room VARCHAR(50),
    capacity INTEGER DEFAULT 50,
    enrolled_count INTEGER DEFAULT 0,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_course_arrangement_code ON course_arrangement(arrangement_code);

CREATE TABLE IF NOT EXISTS score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20),
    course_arrangement_id BIGINT,
    usual_score DECIMAL(5,2),
    midterm_score DECIMAL(5,2),
    final_score DECIMAL(5,2),
    total_score DECIMAL(5,2),
    gpa DECIMAL(3,2),
    exam_time TIMESTAMP,
    status VARCHAR(20),
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20),
    course_arrangement_id BIGINT,
    attendance_date DATE,
    status VARCHAR(20),
    check_in_time TIME,
    check_out_time TIME,
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leave_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20),
    course_arrangement_id BIGINT,
    leave_type VARCHAR(20),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    reason VARCHAR(500),
    attachment VARCHAR(255),
    status VARCHAR(20),
    workflow_type VARCHAR(20),
    current_node VARCHAR(50),
    final_status VARCHAR(20),
    approver_id BIGINT,
    approve_time TIMESTAMP,
    approve_remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student_course_selection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20),
    course_arrangement_id BIGINT,
    status VARCHAR(20) DEFAULT 'PENDING',
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS announcement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200),
    content CLOB,
    type VARCHAR(20),
    target_role VARCHAR(20),
    target_class_id VARCHAR(16),
    priority INTEGER DEFAULT 0,
    author_id VARCHAR(50),
    view_count INTEGER DEFAULT 0,
    is_top INTEGER DEFAULT 0,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50),
    operation VARCHAR(100),
    method VARCHAR(500),
    params CLOB,
    ip VARCHAR(50),
    duration BIGINT,
    status INTEGER,
    error_msg CLOB,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS college (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_code VARCHAR(32) NOT NULL UNIQUE,
    college_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    status INTEGER DEFAULT 1,
    admin_user_id VARCHAR(50) UNIQUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS major (
    major_code VARCHAR(8) PRIMARY KEY,
    major_name VARCHAR(100) NOT NULL,
    major_abbreviation VARCHAR(4) NOT NULL,
    college_id BIGINT NOT NULL,
    description VARCHAR(255),
    status INTEGER DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    role_code VARCHAR(50) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_code)
);

CREATE TABLE IF NOT EXISTS leave_request_approval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_request_id BIGINT NOT NULL,
    node_code VARCHAR(50),
    approver_user_id VARCHAR(50),
    approver_teacher_id BIGINT,
    decision VARCHAR(20),
    remark VARCHAR(255),
    operate_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leave_request_cc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_request_id BIGINT NOT NULL,
    receiver_user_id VARCHAR(50) NOT NULL,
    receiver_teacher_id BIGINT,
    read_flag INTEGER DEFAULT 0,
    read_time TIMESTAMP,
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_config (
    config_key VARCHAR(64) PRIMARY KEY,
    config_value VARCHAR(255),
    description VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS semester (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_code VARCHAR(32) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_teacher_user_id ON teacher(user_id);
CREATE INDEX IF NOT EXISTS idx_teacher_college_id ON teacher(college_id);
CREATE INDEX IF NOT EXISTS idx_student_user_id ON student(user_id);
CREATE INDEX IF NOT EXISTS idx_student_class_id ON student(class_id);
CREATE INDEX IF NOT EXISTS idx_class_college_id ON class(college_id);
CREATE INDEX IF NOT EXISTS idx_class_major_code ON class(major_code);
CREATE INDEX IF NOT EXISTS idx_major_college_id ON major(college_id);

CREATE INDEX IF NOT EXISTS idx_arrangement_teacher ON course_arrangement(teacher_id);
CREATE INDEX IF NOT EXISTS idx_arrangement_class_semester ON course_arrangement(class_id, semester);

CREATE INDEX IF NOT EXISTS idx_score_student_create ON score(student_id, create_time);
CREATE INDEX IF NOT EXISTS idx_score_arrangement_create ON score(course_arrangement_id, create_time);
CREATE INDEX IF NOT EXISTS idx_score_total_score ON score(total_score);

CREATE INDEX IF NOT EXISTS idx_attendance_student_date ON attendance(student_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_arrangement_date ON attendance(course_arrangement_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_status_date ON attendance(status, attendance_date);

CREATE INDEX IF NOT EXISTS idx_leave_student_status_time ON leave_request(student_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_leave_arrangement_status_time ON leave_request(course_arrangement_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_leave_status_time ON leave_request(status, create_time);

CREATE UNIQUE INDEX IF NOT EXISTS uk_student_arrangement ON student_course_selection(student_id, course_arrangement_id);
CREATE INDEX IF NOT EXISTS idx_student_selection_student_id ON student_course_selection(student_id);

CREATE INDEX IF NOT EXISTS idx_announcement_status_time ON announcement(status, create_time);
CREATE INDEX IF NOT EXISTS idx_announcement_target_role ON announcement(target_role);
CREATE INDEX IF NOT EXISTS idx_announcement_time_window ON announcement(start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_sys_log_create_time ON sys_log(create_time);
CREATE INDEX IF NOT EXISTS idx_sys_log_user_time ON sys_log(user_id, create_time);
CREATE INDEX IF NOT EXISTS idx_score_total_create ON score(total_score, create_time);
CREATE INDEX IF NOT EXISTS idx_score_arrangement_total ON score(course_arrangement_id, total_score);
CREATE INDEX IF NOT EXISTS idx_attendance_status_scope_date ON attendance(status, course_arrangement_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_leave_pending_create ON leave_request(status, create_time);
CREATE INDEX IF NOT EXISTS idx_leave_arrangement_pending ON leave_request(course_arrangement_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_leave_node_status ON leave_request(current_node, status);
CREATE INDEX IF NOT EXISTS idx_leave_cc_receiver ON leave_request_cc(receiver_user_id, read_flag);
CREATE INDEX IF NOT EXISTS idx_user_role_user_id ON sys_user_role(user_id);
CREATE INDEX IF NOT EXISTS idx_semester_code ON semester(semester_code);
CREATE INDEX IF NOT EXISTS idx_semester_status ON semester(status);
