-- 学生就业信息表
CREATE TABLE IF NOT EXISTS student_employment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    student_id VARCHAR(20) NOT NULL UNIQUE COMMENT '学号',
    graduation_year YEAR NOT NULL COMMENT '毕业年份',
    employment_status ENUM('EMPLOYED', 'GRADUATE_SCHOOL', 'SELF_EMPLOYED', 'UNEMPLOYED', 'OTHER') NOT NULL DEFAULT 'OTHER' COMMENT '就业状态',
    company_name VARCHAR(200) COMMENT '用人单位名称',
    company_type ENUM('GOVERNMENT', 'STATE_OWNED', 'PRIVATE', 'FOREIGN', 'JOINT_VENTURE', 'OTHER') COMMENT '单位性质',
    industry VARCHAR(100) COMMENT '所属行业',
    position VARCHAR(100) COMMENT '岗位',
    salary_range VARCHAR(50) COMMENT '薪资范围',
    work_city VARCHAR(100) COMMENT '工作城市',
    work_province VARCHAR(100) COMMENT '工作省份',
    contract_type ENUM('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'LABOR_CONTRACT', 'OTHER') COMMENT '合同类型',
    social_insurance TINYINT DEFAULT 0 COMMENT '是否缴纳社保',
    contact_name VARCHAR(50) COMMENT '联系人姓名',
    contact_phone VARCHAR(20) COMMENT '联系人电话',
    contact_email VARCHAR(100) COMMENT '联系人邮箱',
    employment_prove_url VARCHAR(500) COMMENT '就业证明材料URL',
    graduation_school VARCHAR(200) COMMENT '升学学校',
    graduation_major VARCHAR(100) COMMENT '升学专业',
    degree_type ENUM('MASTER', 'DOCTOR', 'OTHER') COMMENT '学位类型',
    remarks TEXT COMMENT '备注',
    recorder_no VARCHAR(20) COMMENT '登记人',
    record_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登记时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_student (student_id),
    INDEX idx_graduation_year (graduation_year),
    INDEX idx_employment_status (employment_status),
    INDEX idx_industry (industry),
    INDEX idx_work_city (work_city),
    CONSTRAINT fk_employment_student FOREIGN KEY (student_id) REFERENCES student(student_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学生就业信息表';

-- 校友信息表
CREATE TABLE IF NOT EXISTS alumni (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    student_id VARCHAR(20) NOT NULL UNIQUE COMMENT '学号',
    name VARCHAR(50) NOT NULL COMMENT '姓名',
    gender TINYINT COMMENT '性别',
    class_code VARCHAR(32) COMMENT '班级代码',
    graduation_year YEAR NOT NULL COMMENT '毕业年份',
    major_code VARCHAR(32) COMMENT '专业代码',
    college_code VARCHAR(32) COMMENT '学院代码',
    phone VARCHAR(20) COMMENT '手机号',
    email VARCHAR(100) COMMENT '邮箱',
    wechat VARCHAR(50) COMMENT '微信号',
    current_company VARCHAR(200) COMMENT '现单位',
    current_position VARCHAR(100) COMMENT '现岗位',
    work_years INT COMMENT '工作年限',
    alumni_association_member TINYINT DEFAULT 0 COMMENT '是否校友会会员',
    volunteer TINYINT DEFAULT 0 COMMENT '是否愿意做志愿者',
    donation TINYINT DEFAULT 0 COMMENT '是否愿意捐赠',
    status TINYINT DEFAULT 1 COMMENT '状态 0-无效 1-有效',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_student (student_id),
    INDEX idx_graduation_year (graduation_year),
    INDEX idx_class (class_code),
    INDEX idx_major (major_code),
    INDEX idx_college (college_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='校友信息表';

-- 就业调查问卷表
CREATE TABLE IF NOT EXISTS employment_survey (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    student_id VARCHAR(20) NOT NULL COMMENT '学号',
    survey_year YEAR NOT NULL COMMENT '调查年份',
    employment_status VARCHAR(50) COMMENT '就业状态',
    company_name VARCHAR(200) COMMENT '单位名称',
    position VARCHAR(100) COMMENT '岗位',
    salary_monthly DECIMAL(10,2) COMMENT '月薪',
    satisfaction_level ENUM('VERY_SATISFIED', 'SATISFIED', 'NEUTRAL', 'DISSATISFIED', 'VERY_DISSATISFIED') COMMENT '满意度',
    major_relevance ENUM('VERY_RELEVANT', 'RELEVANT', 'NEUTRAL', 'IRRELEVANT', 'VERY_IRRELEVANT') COMMENT '专业相关度',
    career_goals TEXT COMMENT '职业发展目标',
    school_feedback TEXT COMMENT '对学校的建议',
    survey_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '调查时间',
    INDEX idx_student_year (student_id, survey_year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='就业调查问卷表';
