package com.student.service.impl;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.student.dto.StudentDTO;
import com.student.entity.Class;
import com.student.entity.Student;
import com.student.entity.SysUser;
import com.student.exception.BusinessException;
import com.student.mapper.ClassMapper;
import com.student.mapper.StudentMapper;
import com.student.mapper.SysUserMapper;
import com.student.security.RoleCode;
import com.student.service.StudentService;
import com.student.service.SysUserService;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.BeanUtils;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.time.LocalDate;
import java.time.Year;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
@RequiredArgsConstructor
public class StudentServiceImpl extends ServiceImpl<StudentMapper, Student> implements StudentService {

    private static final int MAJOR_CODE_LENGTH = 2;
    private static final int SERIAL_LENGTH = 4;
    private static final Pattern TRAILING_SERIAL_PATTERN = Pattern.compile("(\\d{4})$");

    private final StudentMapper studentMapper;
    private final SysUserMapper userMapper;
    private final ClassMapper classMapper;
    private final PasswordEncoder passwordEncoder;
    private final SysUserService sysUserService;

    @Override
    @Transactional
    public void addStudent(StudentDTO studentDTO) {
        boolean autoGenerated = !StringUtils.hasText(studentDTO.getStudentNo());
        String studentNo = autoGenerated ? generateStudentNo(studentDTO.getClassId(), studentDTO.getEnrollmentDate()) : studentDTO.getStudentNo();

        int retries = 0;
        while (studentMapper.selectByStudentNo(studentNo) != null) {
            if (!autoGenerated) {
                throw new BusinessException("Student number already exists");
            }
            if (++retries > 5) {
                throw new BusinessException("Failed to generate unique student number");
            }
            studentNo = generateStudentNo(studentDTO.getClassId(), studentDTO.getEnrollmentDate());
        }
        studentDTO.setStudentNo(studentNo);

        if (!StringUtils.hasText(studentDTO.getPassword())) {
            throw new BusinessException("Password is required for new student");
        }

        SysUser user = new SysUser();
        user.setUsername(studentDTO.getStudentNo());
        user.setPassword(passwordEncoder.encode(studentDTO.getPassword()));
        user.setRealName(studentDTO.getName());
        user.setPhone(studentDTO.getPhone());
        user.setEmail(studentDTO.getEmail());
        user.setRole(SysUser.Role.STUDENT);
        user.setStatus(1);
        userMapper.insert(user);
        sysUserService.grantRole(user.getId(), RoleCode.STUDENT);

        Student student = new Student();
        BeanUtils.copyProperties(studentDTO, student);
        student.setUserId(user.getId());
        student.setStatus(Student.Status.ENROLLED);
        studentMapper.insert(student);

        if (student.getClassId() != null) {
            updateClassStudentCount(student.getClassId());
        }
    }

    @Override
    @Transactional
    public void updateStudent(StudentDTO studentDTO) {
        if (studentDTO.getId() == null) {
            throw new BusinessException("Student ID cannot be null");
        }
        if (!StringUtils.hasText(studentDTO.getStudentNo())) {
            throw new BusinessException("Student number is required");
        }

        Student existStudent = studentMapper.selectById(studentDTO.getId());
        if (existStudent == null) {
            throw new BusinessException("Student not found");
        }

        Student existByNo = studentMapper.selectByStudentNo(studentDTO.getStudentNo());
        if (existByNo != null && !existByNo.getId().equals(studentDTO.getId())) {
            throw new BusinessException("Student number already used");
        }

        String oldClassId = existStudent.getClassId();

        Student student = new Student();
        BeanUtils.copyProperties(studentDTO, student);
        studentMapper.updateById(student);

        SysUser user = new SysUser();
        user.setId(existStudent.getUserId());
        user.setUsername(studentDTO.getStudentNo());
        user.setRealName(studentDTO.getName());
        user.setPhone(studentDTO.getPhone());
        user.setEmail(studentDTO.getEmail());
        if (StringUtils.hasText(studentDTO.getPassword())) {
            user.setPassword(passwordEncoder.encode(studentDTO.getPassword()));
        }
        userMapper.updateById(user);

        if (!Objects.equals(studentDTO.getClassId(), oldClassId)) {
            updateClassStudentCount(oldClassId);
            updateClassStudentCount(studentDTO.getClassId());
        }
    }

    @Override
    public String generateStudentNo(String classId, LocalDate enrollmentDate) {
        if (classId == null) {
            throw new BusinessException("Class is required for student number generation");
        }

        Class clazz = resolveClass(classId);
        if (clazz == null) {
            throw new BusinessException("Class not found");
        }

        int year = resolveEnrollmentYear(clazz, enrollmentDate);
        String majorPrefix = resolveMajorPrefix(clazz);
        String prefix = year + majorPrefix;

        String latestStudentNo = studentMapper.selectLatestStudentNoByPrefix(prefix);
        int nextSerial = resolveNextSerial(latestStudentNo);
        if (nextSerial > 9999) {
            throw new BusinessException("Student number sequence overflow for prefix: " + prefix);
        }

        return prefix + String.format("%0" + SERIAL_LENGTH + "d", nextSerial);
    }

    @Override
    @Transactional
    public void deleteStudent(Long id) {
        Student student = studentMapper.selectById(id);
        if (student == null) {
            throw new BusinessException("Student not found");
        }

        studentMapper.deleteById(id);
        userMapper.deleteById(student.getUserId());

        if (student.getClassId() != null) {
            updateClassStudentCount(student.getClassId());
        }
    }

    @Override
    public Student getStudentById(Long id) {
        return studentMapper.selectByIdWithClass(id);
    }

    @Override
    public Page<Student> getStudentPage(Integer page,
                                        Integer size,
                                        String studentNo,
                                        String name,
                                        String classId,
                                        Long collegeId,
                                        String majorCode,
                                        Student.Status status,
                                        List<String> classIds) {
        Page<Student> pageParam = new Page<>(page, size);
        return studentMapper.selectPageWithClass(pageParam, studentNo, name, classId, collegeId, majorCode, status, classIds);
    }

    @Override
    public List<Student> getStudentsByClassId(String classId) {
        return studentMapper.selectByClassId(classId);
    }

    @Override
    @Transactional
    public void updateStudentStatus(Long id, Student.Status status) {
        Student student = studentMapper.selectById(id);
        if (student == null) {
            throw new BusinessException("Student not found");
        }
        studentMapper.updateStatus(id, status);
    }

    @Override
    public Student getStudentByUserId(Long userId) {
        return lambdaQuery().eq(Student::getUserId, userId).one();
    }

    @Override
    public Map<String, Long> getGenderStatistics() {
        Map<String, Long> result = new HashMap<>();
        result.put("male", 0L);
        result.put("female", 0L);

        List<Map<String, Object>> rows = studentMapper.countByGender();
        for (Map<String, Object> row : rows) {
            Object gender = row.get("gender");
            Object count = row.get("count");
            if (!(count instanceof Number)) {
                continue;
            }

            long value = ((Number) count).longValue();
            if (gender == Student.Gender.MALE || "MALE".equalsIgnoreCase(String.valueOf(gender))) {
                result.put("male", value);
            } else if (gender == Student.Gender.FEMALE || "FEMALE".equalsIgnoreCase(String.valueOf(gender))) {
                result.put("female", value);
            }
        }

        return result;
    }

    private void updateClassStudentCount(String classId) {
        if (classId == null) {
            return;
        }
        Long count = studentMapper.countByClassId(classId);
        Class existing = resolveClass(classId);
        if (existing == null) {
            return;
        }
        Class clazz = new Class();
        clazz.setId(existing.getId());
        clazz.setStudentCount(count == null ? 0 : count.intValue());
        classMapper.updateById(clazz);
    }

    private int resolveEnrollmentYear(Class clazz, LocalDate enrollmentDate) {
        if (enrollmentDate != null) {
            return enrollmentDate.getYear();
        }
        Year grade = clazz.getGrade();
        if (grade != null) {
            return grade.getValue();
        }
        return LocalDate.now().getYear();
    }

    private String resolveMajorPrefix(Class clazz) {
        String majorCode = clazz.getMajorCode();
        String majorLetters = keepLetters(majorCode);
        if (majorLetters.length() >= MAJOR_CODE_LENGTH) {
            return majorLetters.substring(0, MAJOR_CODE_LENGTH);
        }

        String classCode = keepLetters(clazz.getClassCode());
        if (classCode.length() >= MAJOR_CODE_LENGTH) {
            return classCode.substring(0, MAJOR_CODE_LENGTH);
        }
        if (classCode.length() == 1) {
            return classCode + "X";
        }
        return "UN";
    }

    private int resolveNextSerial(String latestStudentNo) {
        if (!StringUtils.hasText(latestStudentNo)) {
            return 1;
        }
        Matcher matcher = TRAILING_SERIAL_PATTERN.matcher(latestStudentNo);
        if (!matcher.find()) {
            return 1;
        }
        return Integer.parseInt(matcher.group(1)) + 1;
    }

    private String keepLetters(String input) {
        if (!StringUtils.hasText(input)) {
            return "";
        }
        return input.replaceAll("[^A-Za-z]", "").toUpperCase();
    }

    private Class resolveClass(String classId) {
        if (!StringUtils.hasText(classId)) {
            return null;
        }
        Class clazz = classMapper.selectByClassCode(classId);
        if (clazz != null) {
            return clazz;
        }
        if (classId.chars().allMatch(Character::isDigit)) {
            return classMapper.selectById(Long.parseLong(classId));
        }
        return null;
    }
}
